rust:
  - changed-files:
      - any-glob-to-any-file: "src/**/*.rs"

ui:
  - changed-files:
      - any-glob-to-any-file:
          - "resources/**"
          - "data/icons/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "*.md"
          - "AGENTS.md"
          - "README.md"
